<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Document extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Document_model');
    } 

    /*
     * Listing of documents
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('document/index?');
        $config['total_rows'] = $this->Document_model->get_all_documents_count();
        $this->pagination->initialize($config);

        $data['documents'] = $this->Document_model->get_all_documents($params);
        
        $data['_view'] = 'document/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new document
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'categorie_id' => $this->input->post('categorie_id'),
				'document_code' => $this->input->post('document_code'),
				'register_date' => $this->input->post('register_date'),
				'reference' => $this->input->post('reference'),
				'topic' => $this->input->post('topic'),
				'store' => $this->input->post('store'),
				'filename' => $this->input->post('filename'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'description' => $this->input->post('description'),
            );
            
            $document_id = $this->Document_model->add_document($params);
            redirect('document/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'document/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a document
     */
    function edit($id)
    {   
        // check if the document exists before trying to edit it
        $data['document'] = $this->Document_model->get_document($id);
        
        if(isset($data['document']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'categorie_id' => $this->input->post('categorie_id'),
					'document_code' => $this->input->post('document_code'),
					'register_date' => $this->input->post('register_date'),
					'reference' => $this->input->post('reference'),
					'topic' => $this->input->post('topic'),
					'store' => $this->input->post('store'),
					'filename' => $this->input->post('filename'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'description' => $this->input->post('description'),
                );

                $this->Document_model->update_document($id,$params);            
                redirect('document/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'document/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The document you are trying to edit does not exist.');
    } 

    /*
     * Deleting document
     */
    function remove($id)
    {
        $document = $this->Document_model->get_document($id);

        // check if the document exists before trying to delete it
        if(isset($document['id']))
        {
            $this->Document_model->delete_document($id);
            redirect('document/index');
        }
        else
            show_error('The document you are trying to delete does not exist.');
    }
    
}
