<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ecdoc_document extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ecdoc_document_model');
    }
}
