<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Org extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!$this->session->userdata('id'))
        {
         redirect('login');
        }
        $this->load->model('Org_model');
    }

    /*
     * Listing of orgs
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('org/index?');
        $config['total_rows'] = $this->Org_model->get_all_orgs_count();
        $this->pagination->initialize($config);

        $data['orgs'] = $this->Org_model->get_all_orgs($params);

        $data['_view'] = 'org/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new org
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'organizatoin' => $this->input->post('organizatoin'),
            );

            $org_id = $this->Org_model->add_org($params);
            redirect('org/index');
        }
        else
        {
            $data['_view'] = 'org/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a org
     */
    function edit($org_id)
    {
        // check if the org exists before trying to edit it
        $data['org'] = $this->Org_model->get_org($org_id);

        if(isset($data['org']['org_id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'organizatoin' => $this->input->post('organizatoin'),
                );

                $this->Org_model->update_org($org_id,$params);
                redirect('org/index');
            }
            else
            {
                $data['_view'] = 'org/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The org you are trying to edit does not exist.');
    }

    /*
     * Deleting org
     */
    function remove($org_id)
    {
        $org = $this->Org_model->get_org($org_id);

        // check if the org exists before trying to delete it
        if(isset($org['org_id']))
        {
            $this->Org_model->delete_org($org_id);
            redirect('org/index');
        }
        else
            show_error('The org you are trying to delete does not exist.');
    }

}
