<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Personel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!$this->session->userdata('id'))
        {
         redirect('login');
        }
        $this->load->model('Personel_model');
    }

    /*
     * Listing of personels
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('personel/index?');
        $data['total_rows'] = $config['total_rows'] = $this->Personel_model->get_all_personels_count();
        $this->pagination->initialize($config);

        $data['personels'] = $this->Personel_model->get_all_personels($params);

        $data['_view'] = 'personel/index';
        $this->load->view('layouts/main',$data);
    }

    function get_personel_by_org($org_id)
    {
        if(isset($org_id))
        {
            $params['limit'] = RECORDS_PER_PAGE;
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

            $config = $this->config->item('pagination');
            //$config['base_url'] = site_url('personel_to_unit/index?');
            $config['total_rows'] = $this->Personel_model->get_all_personel_by_org_count($org_id);
            $this->pagination->initialize($config);

            $data['personels'] = $this->Personel_model->get_all_personel_by_org($org_id,$params);


            if($config['total_rows']>0){

                $data['_view'] = 'personel/selectorg';
                $this->load->view('layouts/main',$data);
            }
            else{
                $_SESSION['message']='ไม่พบข้อมูลค่ะ';
                //echo "<script type='text/javascript'>alert('$message');</script>";
                //$data['_view'] = 'unit/index';
                //$this->load->view('layouts/main');
                redirect('org/index');
            }
        }
        else
            show_error('The personel you are trying to edit does not exist.');
    }


    /*
     * Adding a new personel
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('gov_id','Gov Id','numeric');
		$this->form_validation->set_rules('nation_id','Nation Id','numeric');

		if($this->form_validation->run())
        {
            $params = array(
				'rank_id' => $this->input->post('rank_id'),
				'org_id' => $this->input->post('org_id'),
				'gov_id' => $this->input->post('gov_id'),
				'nation_id' => $this->input->post('nation_id'),
				'name' => $this->input->post('name'),
				'lastname' => $this->input->post('lastname'),
            );

            $personel_id = $this->Personel_model->add_personel($params);
            redirect('personel/index');
        }
        else
        {
			$this->load->model('Rank_model');
			$data['all_rank'] = $this->Rank_model->get_all_rank();

			$this->load->model('Org_model');
			$data['all_orgs'] = $this->Org_model->get_all_orgs();

			$this->load->model('Unit_model');
			$data['all_units'] = $this->Unit_model->get_all_units();

            $data['_view'] = 'personel/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a personel
     */
    function edit($personel_id)
    {
        // check if the personel exists before trying to edit it
        $data['personel'] = $this->Personel_model->get_personel($personel_id);

        if(isset($data['personel']['personel_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('gov_id','Gov Id','numeric');
			$this->form_validation->set_rules('nation_id','Nation Id','numeric');

			if($this->form_validation->run())
            {
                $params = array(
					'rank_id' => $this->input->post('rank_id'),
					'org_id' => $this->input->post('org_id'),
					'gov_id' => $this->input->post('gov_id'),
					'nation_id' => $this->input->post('nation_id'),
					'name' => $this->input->post('name'),
					'lastname' => $this->input->post('lastname'),
                );

                $this->Personel_model->update_personel($personel_id,$params);
                redirect('personel/index');
            }
            else
            {
				$this->load->model('Rank_model');
				$data['all_rank'] = $this->Rank_model->get_all_rank();

				$this->load->model('Org_model');
				$data['all_orgs'] = $this->Org_model->get_all_orgs();

				$this->load->model('Unit_model');
				$data['all_units'] = $this->Unit_model->get_all_units();

                $data['_view'] = 'personel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The personel you are trying to edit does not exist.');
    }

    /*
     * Deleting personel
     */
    function remove($personel_id)
    {
        $personel = $this->Personel_model->get_personel($personel_id);

        // check if the personel exists before trying to delete it
        if(isset($personel['personel_id']))
        {
            $this->Personel_model->delete_personel($personel_id);
            redirect('personel/index');
        }
        else
            show_error('The personel you are trying to delete does not exist.');
    }

}
