<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!$this->session->userdata('id'))
        {
         redirect('login');
        }
        $this->load->model('Role_model');
    }

    /*
     * Listing of roles
     */
    function index()
    {
        $data['roles'] = $this->Role_model->get_all_roles();

        $data['_view'] = 'role/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new role
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'role' => $this->input->post('role'),
            );

            $role_id = $this->Role_model->add_role($params);
            redirect('role/index');
        }
        else
        {
            $data['_view'] = 'role/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a role
     */
    function edit($roleId)
    {
        // check if the role exists before trying to edit it
        $data['role'] = $this->Role_model->get_role($roleId);

        if(isset($data['role']['roleId']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'role' => $this->input->post('role'),
                );

                $this->Role_model->update_role($roleId,$params);
                redirect('role/index');
            }
            else
            {
                $data['_view'] = 'role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The role you are trying to edit does not exist.');
    }

    /*
     * Deleting role
     */
    function remove($roleId)
    {
        $role = $this->Role_model->get_role($roleId);

        // check if the role exists before trying to delete it
        if(isset($role['roleId']))
        {
            $this->Role_model->delete_role($roleId);
            redirect('role/index');
        }
        else
            show_error('The role you are trying to delete does not exist.');
    }

}
