<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_reset_password extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_reset_password_model');
    }
}
