<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Document_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get document by id
     */
    function get_document($id)
    {
        return $this->db->get_where('ecdoc_documents',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all documents count
     */
    function get_all_documents_count()
    {
        $this->db->from('ecdoc_documents');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all documents
     */
    function get_all_documents($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ecdoc_documents')->result_array();
    }
        
    /*
     * function to add new document
     */
    function add_document($params)
    {
        $this->db->insert('ecdoc_documents',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update document
     */
    function update_document($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ecdoc_documents',$params);
    }
    
    /*
     * function to delete document
     */
    function delete_document($id)
    {
        return $this->db->delete('ecdoc_documents',array('id'=>$id));
    }
}
