<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ecdoc_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ecdoc_category by id
     */
    function get_ecdoc_category($id)
    {
        return $this->db->get_where('ecdoc_categories',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all ecdoc_categories
     */
    function get_all_ecdoc_categories()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('ecdoc_categories')->result_array();
    }
        
    /*
     * function to add new ecdoc_category
     */
    function add_ecdoc_category($params)
    {
        $this->db->insert('ecdoc_categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ecdoc_category
     */
    function update_ecdoc_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ecdoc_categories',$params);
    }
    
    /*
     * function to delete ecdoc_category
     */
    function delete_ecdoc_category($id)
    {
        return $this->db->delete('ecdoc_categories',array('id'=>$id));
    }
}
