<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ecdoc_document_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ecdoc_document by id
     */
    function get_ecdoc_document($id)
    {
        return $this->db->get_where('ecdoc_documents',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all ecdoc_documents
     */
    function get_all_ecdoc_documents()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('ecdoc_documents')->result_array();
    }
        
    /*
     * function to add new ecdoc_document
     */
    function add_ecdoc_document($params)
    {
        $this->db->insert('ecdoc_documents',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ecdoc_document
     */
    function update_ecdoc_document($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ecdoc_documents',$params);
    }
    
    /*
     * function to delete ecdoc_document
     */
    function delete_ecdoc_document($id)
    {
        return $this->db->delete('ecdoc_documents',array('id'=>$id));
    }
}
