<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Org_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get org by org_id
     */
    function get_org($org_id)
    {
        return $this->db->get_where('tbl_org',array('org_id'=>$org_id))->row_array();
    }

    /*
     * Get all orgs count
     */
    function get_all_orgs_count()
    {
        $this->db->from('tbl_org');
        return $this->db->count_all_results();
    }

    /*
     * Get all orgs
     */
    function get_all_orgs($params = array())
    {
        $this->db->order_by('organizatoin', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_org')->result_array();
    }

    /*
     * function to add new org
     */
    function add_org($params)
    {
        $this->db->insert('tbl_org',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update org
     */
    function update_org($org_id,$params)
    {
        $this->db->where('org_id',$org_id);
        return $this->db->update('tbl_org',$params);
    }

    /*
     * function to delete org
     */
    function delete_org($org_id)
    {
        return $this->db->delete('tbl_org',array('org_id'=>$org_id));
    }
}
