<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Personel_to_unit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get personel_to_unit by id
     */
    function get_personel_to_unit($id)
    {
        $this->db->select('BaseTbl.id, Unit.unit_name,Unit.unit_id, BaseTbl.year, BaseTbl.position_no, BaseTbl.position,Rank.rank,Rank.rank_id,Personel.personel_id,Personel.name,Personel.lastname');
        $this->db->from('tbl_personel_to_unit as BaseTbl');
        $this->db->join('tbl_unit as Unit', 'Unit.unit_id = BaseTbl.unit_id','left');
        $this->db->join('tbl_rank as Rank', 'Rank.rank_id = BaseTbl.rank_id','left');
        $this->db->join('tbl_personel as Personel', 'Personel.personel_id = BaseTbl.personel_id','left');
        $this->db->order_by('Unit.unit_name', 'ASC');


        //return $this->db->get()->result_array();
        return $this->db->get_where('tbl_personel_to_unit',array('BaseTbl.id'=>$id))->row_array();
    }

    /*
     * Get all personel_to_unit count
     */
    function get_all_personel_to_unit_count()
    {
        $this->db->from('tbl_personel_to_unit');
        return $this->db->count_all_results();
    }
    function get_all_personel_by_unit_count($unit_id)
    {
        $this->db->from('tbl_personel_to_unit');
        $this->db->where('unit_id',$unit_id);
        return $this->db->count_all_results();
    }
    function get_all_rank()
    {
        $this->db->from('tbl_rank');
        return $this->db->get()->result_array();
    }
    /*
     * Get all personel_to_unit
     */
    function get_all_personel_to_unit($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->select('BaseTbl.id, Unit.unit_name,BaseTbl.rank_id, BaseTbl.year, BaseTbl.position_no, BaseTbl.position,Rank.rank,Personel.name,Personel.lastname');
        $this->db->from('tbl_personel_to_unit as BaseTbl');
        $this->db->join('tbl_unit as Unit', 'Unit.unit_id = BaseTbl.unit_id','left');
        $this->db->join('tbl_personel as Personel', 'Personel.personel_id = BaseTbl.personel_id','left');
        $this->db->join('tbl_rank as Rank', 'Rank.rank_id = Personel.rank_id','left');
        $this->db->order_by('BaseTbl.id', 'DESC');

        return $this->db->get()->result_array();

    }
    /*
     * Get personel_by_unit
     */
    function get_all_personel_by_unit($unit_id,$year,$params = array())
    {
        $this->db->where('Unit.unit_id',$unit_id);
        $this->db->where('BaseTbl.year',$year);
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->select('BaseTbl.id, Unit.unit_name, BaseTbl.year, BaseTbl.position_no, BaseTbl.position,Rank.rank,Personel.name,Personel.lastname');
        $this->db->from('tbl_personel_to_unit as BaseTbl');
        $this->db->join('tbl_unit as Unit', 'Unit.unit_id = BaseTbl.unit_id','left');
        $this->db->join('tbl_personel as Personel', 'Personel.personel_id = BaseTbl.personel_id','left');
        $this->db->join('tbl_rank as Rank', 'Rank.rank_id = Personel.rank_id','left');
        $this->db->order_by('BaseTbl.position_no', 'ASC');

        return $this->db->get()->result_array();

    }

    /*
     * Get personel_free not assign yet
     */
    function get_free_personels($year,$params = array())
    {

        // ค้นหารายชื่อที่ถูกจัดไปบรรจุหน่วยในสนามแล้ว
        $this->db->select('personel_id');
        $this->db->from('tbl_personel_to_unit');
        $this->db->where('year',$year);
        $selected_personel=$this->db->get()->result_array();
        foreach($selected_personel as $sp){
            $arr_selected_personel[]= $sp['personel_id'];
        }

        // ค้นหารายชื่อกำลังพลที่ยังไม่ได้บรรจุหน่วย
        $this->db->select('BaseTbl.personel_id, Rank.rank,BaseTbl.name,BaseTbl.lastname');
        $this->db->from('tbl_personel as BaseTbl');
        $this->db->join('tbl_rank as Rank', 'Rank.rank_id = BaseTbl.rank_id','left');
        $this->db->where_not_in('BaseTbl.personel_id',$arr_selected_personel);
        $this->db->order_by('BaseTbl.name', 'ASC');

        return $this->db->get()->result_array();

    }


    /*
     * function to add new personel_to_unit
     */
    function add_personel_to_unit($params)
    {
        $this->db->insert('tbl_personel_to_unit',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update personel_to_unit
     */
    function update_personel_to_unit($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_personel_to_unit',$params);
    }

    /*
     * function to delete personel_to_unit
     */
    function delete_personel_to_unit($id)
    {
        return $this->db->delete('tbl_personel_to_unit',array('id'=>$id));
    }
}
