<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Personel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get personel by personel_id
     */
    function get_personel($personel_id)
    {
        return $this->db->get_where('tbl_personel',array('personel_id'=>$personel_id))->row_array();
    }

    /*
     * Get all personels count
     */
    function get_all_personels_count()
    {
        $this->db->from('tbl_personel');
        return $this->db->count_all_results();
    }
    function get_all_personel_by_org_count($org_id)
    {
        $this->db->from('tbl_personel');
        $this->db->where('org_id',$org_id);
        return $this->db->count_all_results();
    }
    /*
     * Get all personels
     */
    function get_all_personels($params = array())
    {
        $this->db->select('BaseTbl.personel_id, rank.rank, BaseTbl.name, BaseTbl.lastname, BaseTbl.gov_id, BaseTbl.nation_id, org.organizatoin,BaseTbl.is_deleted,unit.unit_name');
        $this->db->from('tbl_personel as BaseTbl');
        $this->db->order_by('BaseTbl.name', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->join('tbl_rank as rank', 'rank.rank_id = BaseTbl.rank_id','left');
        $this->db->join('tbl_org as org', 'org.org_id = BaseTbl.org_id','left');
        $this->db->join('tbl_personel_to_unit as personel_to_unit', 'personel_to_unit.personel_id = BaseTbl.personel_id ','left');
        $this->db->join('tbl_unit as unit', 'personel_to_unit.unit_id = unit.unit_id ','left');
        return $this->db->get()->result_array();
    }

    /*
     * Get all personels
     */
    function get_all_personel_by_org($org_id,$params = array())
    {
        $this->db->select('BaseTbl.personel_id, rank.rank, BaseTbl.name, BaseTbl.lastname, BaseTbl.gov_id, BaseTbl.nation_id, org.organizatoin,BaseTbl.is_deleted,unit.unit_name');
        $this->db->from('tbl_personel as BaseTbl');
        $this->db->where('org.org_id',$org_id);
        $this->db->order_by('BaseTbl.name', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->join('tbl_rank as rank', 'rank.rank_id = BaseTbl.rank_id','left');
        $this->db->join('tbl_org as org', 'org.org_id = BaseTbl.org_id','left');
        $this->db->join('tbl_personel_to_unit as personel_to_unit', 'personel_to_unit.personel_id = BaseTbl.personel_id ','left');
        $this->db->join('tbl_unit as unit', 'personel_to_unit.unit_id = unit.unit_id ','left');
        return $this->db->get()->result_array();
    }

    /*
     * function to add new personel
     */
    function add_personel($params)
    {
        $this->db->insert('tbl_personel',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update personel
     */
    function update_personel($personel_id,$params)
    {
        $this->db->where('personel_id',$personel_id);
        return $this->db->update('tbl_personel',$params);
    }

    /*
     * function to delete personel
     */
    function delete_personel($personel_id)
    {
        return $this->db->delete('tbl_personel',array('personel_id'=>$personel_id));
    }
}
