<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rank_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rank by rank_id
     */
    function get_rank($rank_id)
    {
        return $this->db->get_where('tbl_rank',array('rank_id'=>$rank_id))->row_array();
    }
        
    /*
     * Get all rank
     */
    function get_all_rank()
    {
        $this->db->order_by('rank_id', 'desc');
        return $this->db->get('tbl_rank')->result_array();
    }
        
    /*
     * function to add new rank
     */
    function add_rank($params)
    {
        $this->db->insert('tbl_rank',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rank
     */
    function update_rank($rank_id,$params)
    {
        $this->db->where('rank_id',$rank_id);
        return $this->db->update('tbl_rank',$params);
    }
    
    /*
     * function to delete rank
     */
    function delete_rank($rank_id)
    {
        return $this->db->delete('tbl_rank',array('rank_id'=>$rank_id));
    }
}
