<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get role by roleId
     */
    function get_role($roleId)
    {
        return $this->db->get_where('tbl_roles',array('roleId'=>$roleId))->row_array();
    }

    /*
     * Get all roles
     */
    function get_all_roles()
    {
        $this->db->order_by('role', 'asc');
        return $this->db->get('tbl_roles')->result_array();
    }

    /*
     * function to add new role
     */
    function add_role($params)
    {
        $this->db->insert('tbl_roles',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update role
     */
    function update_role($roleId,$params)
    {
        $this->db->where('roleId',$roleId);
        return $this->db->update('tbl_roles',$params);
    }

    /*
     * function to delete role
     */
    function delete_role($roleId)
    {
        return $this->db->delete('tbl_roles',array('roleId'=>$roleId));
    }
}
