<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Unit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get unit by unit_id
     */
    function get_unit($unit_id)
    {
        return $this->db->get_where('tbl_unit',array('unit_id'=>$unit_id))->row_array();
    }

    /*
     * Get all units count
     */
    function get_all_units_count()
    {
        $this->db->from('tbl_unit');
        return $this->db->count_all_results();
    }

    /*
     * Get all units
     */
    function get_all_units($params = array())
    {
        $this->db->order_by('unit_name', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_unit')->result_array();
    }

    /*
     * function to add new unit
     */
    function add_unit($params)
    {
        $this->db->insert('tbl_unit',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update unit
     */
    function update_unit($unit_id,$params)
    {
        $this->db->where('unit_id',$unit_id);
        return $this->db->update('tbl_unit',$params);
    }

    /*
     * function to delete unit
     */
    function delete_unit($unit_id)
    {
        return $this->db->delete('tbl_unit',array('unit_id'=>$unit_id));
    }
}
